### ISSUE TITLE
Insights for Twitter 

### ISSUE THREAD

**Issue by wilsonwong13** [jeancarl/node-red-labs#2]
I don't know if this was a recent change but when I make the get request, I keep getting "JSON parse error" for Insights for Twitter.

**Comment by jeancarl** [comment]
The Insights for Twitter service has reached End of Support date. Please see the blog post here for alternatives:
https://www.ibm.com/blogs/bluemix/2017/03/retirement-insights-twitter-service/

**Comment by wilsonwong13** [comment]
O thanks!
